using Recipes.Models;

namespace Recipes.Database.SeedData;

public static class RecipeSeed
{

    private static readonly DateTime SeedDate = new(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc);
    public static readonly Recipe[] Recipes =
    [
        new Recipe
        {
            Id = 1,
            UserId = 1,
            Name = "Classic Pancakes",
            Description = "Fluffy pancakes perfect for breakfast.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 1,
            Ingredients = ["2 cups flour", "2 eggs", "1.5 cups milk", "2 tbsp sugar", "1 tsp baking powder", "Pinch of salt"],
            Instructions = ["Mix dry ingredients.", "Add eggs and milk.", "Whisk until smooth.", "Cook on griddle until golden."],
            Image = "",
            Tags = ["breakfast", "pancakes"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 20,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 2,
            UserId = 1,
            Name = "Chicken Caesar Salad",
            Description = "A healthy lunch salad with grilled chicken.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 2,
            Ingredients = ["2 chicken breasts", "Romaine lettuce", "Caesar dressing", "Croutons", "Parmesan cheese"],
            Instructions = ["Grill chicken.", "Chop lettuce.", "Mix all ingredients.", "Top with dressing and cheese."],
            Image = "",
            Tags = ["lunch", "salad"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 25,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 3,
            UserId = 1,
            Name = "Spaghetti Bolognese",
            Description = "Classic Italian pasta dish with rich meat sauce.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 3,
            Ingredients = ["200g spaghetti", "100g ground beef", "1 can tomato sauce", "1 onion", "2 cloves garlic", "Olive oil", "Salt", "Pepper"],
            Instructions = ["Cook spaghetti.", "Sauté onion and garlic.", "Add beef and cook until brown.", "Pour in tomato sauce and simmer.", "Serve sauce over spaghetti."],
            Image = "",
            Tags = ["dinner", "pasta"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 40,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 4,
            UserId = 1,
            Name = "Chocolate Chip Cookies",
            Description = "Chewy cookies loaded with chocolate chips.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 4,
            Ingredients = ["1 cup butter", "1 cup sugar", "2 cups flour", "2 eggs", "1 tsp vanilla", "1 tsp baking soda", "2 cups chocolate chips"],
            Instructions = ["Preheat oven to 350°F (175°C).", "Cream butter and sugar.", "Add eggs and vanilla.", "Mix in flour and baking soda.", "Fold in chocolate chips.", "Drop by spoonfuls onto baking sheet.", "Bake for 10-12 minutes."],
            Image = "",
            Tags = ["snack", "cookies"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 30,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 5,
            UserId = 1,
            Name = "Caprese Salad",
            Description = "Fresh salad with tomatoes, mozzarella, and basil.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 2,
            Ingredients = ["4 tomatoes", "200g mozzarella", "Fresh basil", "Olive oil", "Salt", "Pepper"],
            Instructions = ["Slice tomatoes and mozzarella.", "Layer with basil leaves.", "Drizzle with olive oil.", "Season with salt and pepper."],
            Image = "",
            Tags = ["lunch", "salad"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 15,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 6,
            UserId = 1,
            Name = "Vegetable Stir-Fry",
            Description = "Quick and healthy vegetable stir-fry.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 3,
            Ingredients = ["Mixed vegetables (bell peppers, broccoli, carrots)", "2 tbsp soy sauce", "1 tbsp olive oil", "2 cloves garlic", "1 tsp ginger"],
            Instructions = ["Heat oil in a pan.", "Add garlic and ginger, sauté for 1 minute.", "Add vegetables and stir-fry until tender.", "Add soy sauce and cook for another 2 minutes."],
            Image = "",
            Tags = ["dinner", "vegetarian"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 20,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 7,
            UserId = 1,
            Name = "Avocado Toast",
            Description = "Simple and nutritious breakfast toast with avocado.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 1,
            Ingredients = ["2 slices whole-grain bread", "1 ripe avocado", "Salt", "Pepper", "Lemon juice", "Chili flakes (optional)", "Olive oil (optional)"],
            Instructions = ["Toast the bread.", "Mash avocado with lemon juice, salt, and pepper.", "Spread on toast.", "Drizzle with olive oil and sprinkle chili flakes if using."],
            Image = "",
            Tags = ["breakfast", "quick"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 10,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 8,
            UserId = 1,
            Name = "Cheese Omelette",
            Description = "Fluffy omelette filled with cheese.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 1,
            Ingredients = ["3 eggs", "2 tbsp milk", "1/2 cup shredded cheese", "1 tbsp butter", "Salt", "Pepper"],
            Instructions = ["Whisk eggs, milk, salt, and pepper.", "Melt butter in a pan.", "Pour eggs and cook until almost set.", "Add cheese, fold, and cook until melted."],
            Image = "",
            Tags = ["breakfast", "eggs"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 12,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 9,
            UserId = 1,
            Name = "French Toast",
            Description = "Classic cinnamon vanilla French toast.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 1,
            Ingredients = ["4 slices bread", "2 eggs", "1/2 cup milk", "1 tsp vanilla", "1/2 tsp cinnamon", "Butter", "Maple syrup"],
            Instructions = ["Whisk eggs, milk, vanilla, and cinnamon.", "Dip bread in mixture.", "Cook on buttered skillet until golden on both sides.", "Serve with maple syrup."],
            Image = "",
            Tags = ["breakfast", "sweet"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 15,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 10,
            UserId = 1,
            Name = "Berry Smoothie Bowl",
            Description = "Thick smoothie bowl topped with fruit and granola.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 1,
            Ingredients = ["1 cup frozen berries", "1 banana", "1/2 cup yogurt", "1/2 cup milk", "Granola", "Fresh fruit", "Chia seeds"],
            Instructions = ["Blend berries, banana, yogurt, and milk until thick.", "Pour into a bowl.", "Top with granola, fresh fruit, and chia seeds."],
            Image = "",
            Tags = ["breakfast", "smoothie"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 8,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 11,
            UserId = 1,
            Name = "Granola Parfait",
            Description = "Layered yogurt parfait with granola and honey.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 1,
            Ingredients = ["1 cup yogurt", "1/2 cup granola", "1/2 cup mixed berries", "1 tbsp honey"],
            Instructions = ["Layer yogurt, granola, and berries in a glass.", "Drizzle honey on top.", "Serve immediately."],
            Image = "",
            Tags = ["breakfast", "no-cook"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 5,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 12,
            UserId = 1,
            Name = "Turkey Club Sandwich",
            Description = "Hearty triple-decker turkey club.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 2,
            Ingredients = ["3 slices bread", "Sliced turkey", "Bacon", "Lettuce", "Tomato", "Mayonnaise", "Butter"],
            Instructions = ["Toast bread and spread with mayo.", "Layer turkey, bacon, lettuce, and tomato.", "Stack and slice in half."],
            Image = "",
            Tags = ["lunch", "sandwich"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 15,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 13,
            UserId = 1,
            Name = "Quinoa Veggie Salad",
            Description = "Protein-packed quinoa salad with fresh veggies.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 2,
            Ingredients = ["1 cup cooked quinoa", "Cherry tomatoes", "Cucumber", "Red onion", "Feta cheese", "Olives", "Olive oil", "Lemon juice", "Salt", "Pepper"],
            Instructions = ["Combine cooked quinoa and chopped vegetables.", "Crumble in feta and add olives.", "Dress with olive oil, lemon juice, salt, and pepper.", "Toss and serve."],
            Image = "",
            Tags = ["lunch", "vegetarian"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 20,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 14,
            UserId = 1,
            Name = "Creamy Tomato Soup",
            Description = "Comforting tomato soup with a touch of cream.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 2,
            Ingredients = ["1 tbsp olive oil", "1 onion", "2 cloves garlic", "1 can crushed tomatoes", "1 cup vegetable broth", "1/4 cup cream", "Salt", "Pepper", "Basil"],
            Instructions = ["Sauté onion and garlic in olive oil.", "Add tomatoes and broth; simmer 10 minutes.", "Blend until smooth.", "Stir in cream, season, and garnish with basil."],
            Image = "",
            Tags = ["lunch", "soup"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 25,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 15,
            UserId = 1,
            Name = "Veggie Wrap",
            Description = "Colorful veggie wrap with hummus.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 2,
            Ingredients = ["Large tortilla", "Hummus", "Bell peppers", "Cucumber", "Spinach", "Carrots", "Avocado", "Salt", "Pepper"],
            Instructions = ["Spread hummus on tortilla.", "Layer sliced veggies and avocado.", "Season, roll tightly, and slice in half."],
            Image = "",
            Tags = ["lunch", "vegan"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 10,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 16,
            UserId = 1,
            Name = "Tuna Salad",
            Description = "Classic tuna salad perfect for sandwiches or greens.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 2,
            Ingredients = ["1 can tuna", "2 tbsp mayo", "1 tbsp mustard", "Celery", "Red onion", "Salt", "Pepper", "Lemon juice"],
            Instructions = ["Drain tuna and combine with chopped celery and onion.", "Mix in mayo, mustard, and lemon juice.", "Season with salt and pepper.", "Serve as a sandwich or over greens."],
            Image = "",
            Tags = ["lunch", "seafood"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 10,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 17,
            UserId = 1,
            Name = "Beef Tacos",
            Description = "Seasoned ground beef tacos with fresh toppings.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 3,
            Ingredients = ["500g ground beef", "Taco seasoning", "Taco shells", "Lettuce", "Tomato", "Cheddar", "Sour cream", "Salsa"],
            Instructions = ["Cook beef with taco seasoning.", "Warm taco shells.", "Assemble with toppings and serve."],
            Image = "",
            Tags = ["dinner", "mexican"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 25,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 18,
            UserId = 1,
            Name = "Grilled Salmon",
            Description = "Lemon garlic grilled salmon fillets.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 3,
            Ingredients = ["2 salmon fillets", "2 tbsp olive oil", "2 cloves garlic", "Lemon", "Salt", "Pepper", "Fresh dill"],
            Instructions = ["Brush salmon with oil, garlic, salt, and pepper.", "Grill 3-4 minutes per side.", "Serve with lemon wedges and dill."],
            Image = "",
            Tags = ["dinner", "seafood"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 20,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 19,
            UserId = 1,
            Name = "Chicken Curry",
            Description = "Creamy coconut chicken curry.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 3,
            Ingredients = ["500g chicken", "1 onion", "2 cloves garlic", "1 tbsp curry powder", "1 tsp ginger", "1 can coconut milk", "Oil", "Salt"],
            Instructions = ["Sauté onion, garlic, and ginger.", "Add chicken and brown.", "Stir in curry powder.", "Pour coconut milk and simmer until cooked."],
            Image = "",
            Tags = ["dinner", "curry"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 35,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 20,
            UserId = 1,
            Name = "Vegetable Lasagna",
            Description = "Layers of pasta with veggies and cheese.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 3,
            Ingredients = ["Lasagna noodles", "Marinara sauce", "Zucchini", "Spinach", "Ricotta", "Mozzarella", "Parmesan", "Olive oil", "Salt", "Pepper"],
            Instructions = ["Sauté zucchini and spinach.", "Layer noodles, sauce, veggies, and cheeses.", "Bake at 375°F (190°C) for 30-35 minutes."],
            Image = "",
            Tags = ["dinner", "vegetarian"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 50,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 21,
            UserId = 1,
            Name = "Shrimp Fried Rice",
            Description = "Quick fried rice with shrimp and vegetables.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 3,
            Ingredients = ["2 cups cooked rice", "200g shrimp", "Frozen peas and carrots", "2 eggs", "Soy sauce", "Sesame oil", "Green onions", "Garlic"],
            Instructions = ["Scramble eggs and set aside.", "Stir-fry garlic, shrimp, and veggies.", "Add rice, soy sauce, and sesame oil.", "Stir in eggs and green onions."],
            Image = "",
            Tags = ["dinner", "stir-fry"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 20,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 22,
            UserId = 1,
            Name = "Beef Stir-Fry",
            Description = "Tender beef with vegetables in a savory sauce.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 3,
            Ingredients = ["300g beef strips", "Broccoli", "Bell peppers", "Soy sauce", "Garlic", "Ginger", "Cornstarch", "Vegetable oil"],
            Instructions = ["Marinate beef in soy sauce and cornstarch.", "Stir-fry beef until browned; remove.", "Cook veggies with garlic and ginger.", "Return beef, add sauce, and toss."],
            Image = "",
            Tags = ["dinner", "asian"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 25,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 23,
            UserId = 1,
            Name = "Margherita Pizza",
            Description = "Classic pizza with tomato, mozzarella, and basil.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 3,
            Ingredients = ["Pizza dough", "Tomato sauce", "Fresh mozzarella", "Fresh basil", "Olive oil", "Salt"],
            Instructions = ["Preheat oven to highest setting.", "Stretch dough and spread sauce.", "Top with mozzarella and bake until bubbly.", "Garnish with basil and olive oil."],
            Image = "",
            Tags = ["dinner", "pizza"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 20,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 24,
            UserId = 1,
            Name = "Lentil Stew",
            Description = "Hearty lentil stew with vegetables.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 3,
            Ingredients = ["1 cup lentils", "1 onion", "2 carrots", "2 celery stalks", "2 cloves garlic", "1 can diced tomatoes", "Vegetable broth", "Bay leaf", "Salt", "Pepper"],
            Instructions = ["Sauté onion, carrots, and celery.", "Add garlic, lentils, tomatoes, broth, and bay leaf.", "Simmer until lentils are tender.", "Season and serve."],
            Image = "",
            Tags = ["dinner", "vegan"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 45,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 25,
            UserId = 1,
            Name = "Stuffed Bell Peppers",
            Description = "Bell peppers filled with rice and beef.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 3,
            Ingredients = ["4 bell peppers", "1 cup cooked rice", "300g ground beef", "1 onion", "Tomato sauce", "Cheddar", "Salt", "Pepper"],
            Instructions = ["Sauté beef and onion; mix with rice and sauce.", "Stuff peppers and top with cheese.", "Bake at 375°F (190°C) for 25-30 minutes."],
            Image = "",
            Tags = ["dinner", "bake"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 40,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 26,
            UserId = 1,
            Name = "Guacamole",
            Description = "Creamy avocado dip with lime and cilantro.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 4,
            Ingredients = ["2 ripe avocados", "1/2 onion", "1 tomato", "1 lime", "Cilantro", "Salt", "Pepper"],
            Instructions = ["Mash avocados.", "Stir in finely chopped onion, tomato, and cilantro.", "Add lime juice, salt, and pepper to taste."],
            Image = "",
            Tags = ["snack", "dip"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 10,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 27,
            UserId = 1,
            Name = "Classic Hummus",
            Description = "Smooth chickpea hummus with tahini.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 4,
            Ingredients = ["1 can chickpeas", "2 tbsp tahini", "1 clove garlic", "2 tbsp olive oil", "Lemon juice", "Salt", "Paprika"],
            Instructions = ["Blend chickpeas, tahini, garlic, lemon juice, and salt.", "Stream in olive oil until smooth.", "Garnish with paprika."],
            Image = "",
            Tags = ["snack", "vegan"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 10,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 28,
            UserId = 1,
            Name = "Bruschetta",
            Description = "Toasted bread topped with tomato and basil.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 4,
            Ingredients = ["Baguette", "Tomatoes", "Garlic", "Basil", "Olive oil", "Salt", "Pepper", "Balsamic glaze (optional)"],
            Instructions = ["Toast sliced baguette.", "Mix chopped tomatoes with garlic, basil, oil, salt, and pepper.", "Spoon onto toast and drizzle glaze if desired."],
            Image = "",
            Tags = ["snack", "appetizer"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 15,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 29,
            UserId = 1,
            Name = "Banana Bread",
            Description = "Moist banana bread loaf with walnuts.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 4,
            Ingredients = ["3 ripe bananas", "1/3 cup melted butter", "3/4 cup sugar", "1 egg", "1 tsp vanilla", "1 tsp baking soda", "Pinch of salt", "1.5 cups flour", "1/2 cup walnuts"],
            Instructions = ["Mash bananas and mix with butter and sugar.", "Beat in egg and vanilla.", "Stir in baking soda, salt, and flour.", "Fold in walnuts.", "Bake in loaf pan at 350°F (175°C) for 50-60 minutes."],
            Image = "",
            Tags = ["snack", "bake"],
            CookingTimeHours = 1,
            CookingTimeMinutes = 0,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 30,
            UserId = 1,
            Name = "Chocolate Brownies",
            Description = "Fudgy chocolate brownies with crackly top.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 4,
            Ingredients = ["1/2 cup butter", "1 cup sugar", "2 eggs", "1 tsp vanilla", "1/3 cup cocoa powder", "1/2 cup flour", "1/4 tsp salt", "1/4 tsp baking powder"],
            Instructions = ["Melt butter and mix with sugar.", "Beat in eggs and vanilla.", "Stir in dry ingredients.", "Bake at 350°F (175°C) for 20-25 minutes."],
            Image = "",
            Tags = ["snack", "chocolate"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 30,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        // --- Additional recipes to round out categories ---
        new Recipe
        {
            Id = 31,
            UserId = 1,
            Name = "Breakfast Burrito",
            Description = "Eggs, potatoes, and cheese wrapped in a warm tortilla.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 1,
            Ingredients = ["Large tortilla", "2 eggs", "1/2 cup diced potatoes", "1/4 cup shredded cheese", "Salsa", "Salt", "Pepper", "Oil"],
            Instructions = ["Cook diced potatoes in oil until tender.", "Scramble eggs and season.", "Warm tortilla and fill with potatoes, eggs, cheese, and salsa.", "Roll up and serve."],
            Image = "",
            Tags = ["breakfast", "wrap"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 20,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 32,
            UserId = 1,
            Name = "Baked Oatmeal",
            Description = "Warm baked oats with berries and cinnamon.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 1,
            Ingredients = ["2 cups rolled oats", "1 tsp baking powder", "1 tsp cinnamon", "Pinch of salt", "2 cups milk", "1 egg", "2 tbsp maple syrup", "1 cup mixed berries"],
            Instructions = ["Preheat oven to 350°F (175°C).", "Mix dry ingredients.", "Whisk milk, egg, and maple syrup.", "Combine with oats and fold in berries.", "Bake 30–35 minutes until set."],
            Image = "",
            Tags = ["breakfast", "oats"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 40,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 33,
            UserId = 1,
            Name = "Shakshuka",
            Description = "Eggs poached in a spiced tomato pepper sauce.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 1,
            Ingredients = ["2 tbsp olive oil", "1 onion", "1 bell pepper", "2 cloves garlic", "1 tsp cumin", "1 tsp paprika", "1 can crushed tomatoes", "4 eggs", "Salt", "Pepper", "Parsley"],
            Instructions = ["Sauté onion and pepper in oil.", "Add garlic and spices.", "Pour in tomatoes and simmer.", "Make wells and crack eggs; cover until set.", "Season and garnish with parsley."],
            Image = "",
            Tags = ["breakfast", "eggs"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 30,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 34,
            UserId = 1,
            Name = "Overnight Oats",
            Description = "No-cook oats soaked overnight with chia and fruit.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 1,
            Ingredients = ["1/2 cup rolled oats", "1 tbsp chia seeds", "1/2 cup milk", "1/4 cup yogurt", "1 tsp honey", "Fresh fruit"],
            Instructions = ["Combine oats, chia, milk, yogurt, and honey in a jar.", "Stir, cover, and refrigerate overnight.", "Top with fruit before serving."],
            Image = "",
            Tags = ["breakfast", "no-cook"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 5,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 35,
            UserId = 1,
            Name = "Greek Salad",
            Description = "Crisp cucumber, tomato, olives, and feta with oregano.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 2,
            Ingredients = ["Cucumber", "Tomatoes", "Red onion", "Kalamata olives", "Feta", "Olive oil", "Red wine vinegar", "Oregano", "Salt", "Pepper"],
            Instructions = ["Chop vegetables and combine with olives and feta.", "Dress with oil, vinegar, oregano, salt, and pepper.", "Toss and serve."],
            Image = "",
            Tags = ["lunch", "salad"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 15,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 36,
            UserId = 1,
            Name = "BLT Sandwich",
            Description = "Classic bacon, lettuce, and tomato on toasted bread.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 2,
            Ingredients = ["2 slices bread", "Bacon", "Lettuce", "Tomato", "Mayonnaise", "Salt", "Pepper"],
            Instructions = ["Cook bacon until crisp.", "Toast bread and spread with mayo.", "Layer bacon, lettuce, and tomato; season and serve."],
            Image = "",
            Tags = ["lunch", "sandwich"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 12,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 37,
            UserId = 1,
            Name = "Minestrone Soup",
            Description = "Hearty Italian vegetable and bean soup.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 2,
            Ingredients = ["Olive oil", "Onion", "Carrot", "Celery", "Garlic", "Diced tomatoes", "Vegetable broth", "Cannellini beans", "Small pasta", "Zucchini", "Spinach", "Salt", "Pepper"],
            Instructions = ["Sauté onion, carrot, celery, and garlic.", "Add tomatoes and broth; simmer.", "Stir in beans and pasta; cook until tender.", "Add zucchini and spinach; season and serve."],
            Image = "",
            Tags = ["lunch", "soup"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 35,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 38,
            UserId = 1,
            Name = "Trail Mix",
            Description = "Customizable nuts, seeds, dried fruit, and chocolate.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 4,
            Ingredients = ["Almonds", "Cashews", "Pumpkin seeds", "Raisins", "Dried cranberries", "Dark chocolate chips", "Sea salt"],
            Instructions = ["Combine all ingredients in a bowl.", "Toss to mix and store in an airtight container."],
            Image = "",
            Tags = ["snack", "no-cook"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 5,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 39,
            UserId = 1,
            Name = "Fruit Salad",
            Description = "Fresh seasonal fruit with a honey-lime dressing.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 4,
            Ingredients = ["Strawberries", "Blueberries", "Pineapple", "Grapes", "Kiwi", "Honey", "Lime juice", "Mint"],
            Instructions = ["Chop fruit and combine in a bowl.", "Whisk honey with lime juice.", "Pour over fruit and toss with chopped mint."],
            Image = "",
            Tags = ["snack", "fruit"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 10,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 40,
            UserId = 1,
            Name = "Cheese and Crackers",
            Description = "Simple snack board with assorted cheeses and crackers.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 4,
            Ingredients = ["Assorted crackers", "Cheddar", "Brie", "Gouda", "Grapes", "Honey"],
            Instructions = ["Arrange cheeses and crackers on a board.", "Add grapes and a drizzle of honey."],
            Image = "",
            Tags = ["snack", "board"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 5,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 41,
            UserId = 1,
            Name = "Yogurt Ranch Dip with Veggies",
            Description = "Greek yogurt ranch dip served with crunchy vegetables.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 4,
            Ingredients = ["1 cup Greek yogurt", "1 tsp dried dill", "1/2 tsp garlic powder", "1/2 tsp onion powder", "1 tsp lemon juice", "Salt", "Pepper", "Assorted veggie sticks"],
            Instructions = ["Mix yogurt with dill, garlic and onion powder, and lemon juice.", "Season with salt and pepper.", "Serve with veggie sticks."],
            Image = "",
            Tags = ["snack", "dip"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 7,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 42,
            UserId = 1,
            Name = "Breakfast Quesadilla",
            Description = "Crispy tortilla filled with scrambled eggs, cheese, and veggies.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 1,
            Ingredients = ["Large tortilla", "2 eggs", "1/3 cup shredded cheese", "Bell peppers", "Spinach", "Butter or oil", "Salt", "Pepper", "Salsa (optional)"],
            Instructions = ["Scramble eggs and season.", "Warm tortilla in a pan; add cheese, eggs, and veggies.", "Fold and cook until golden on both sides.", "Serve with salsa if desired."],
            Image = "",
            Tags = ["breakfast", "wrap"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 15,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 43,
            UserId = 1,
            Name = "Mediterranean Chickpea Bowl",
            Description = "Protein-packed bowl with chickpeas, veggies, and lemon-tahini dressing.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 2,
            Ingredients = ["1 can chickpeas", "Cherry tomatoes", "Cucumber", "Red onion", "Kalamata olives", "Parsley", "Feta (optional)", "Olive oil", "Lemon juice", "Tahini", "Salt", "Pepper"],
            Instructions = ["Rinse and drain chickpeas.", "Chop vegetables and parsley.", "Whisk olive oil, lemon juice, tahini, salt, and pepper.", "Combine all and toss with dressing; top with feta if using."],
            Image = "",
            Tags = ["lunch", "vegetarian"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 15,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        },
        new Recipe
        {
            Id = 44,
            UserId = 1,
            Name = "Peanut Butter Energy Bites",
            Description = "No-bake oats, peanut butter, and honey bites.",
            CurrentStatus = RecipeStatus.Approved,
            CategoryId = 4,
            Ingredients = ["1 cup rolled oats", "1/2 cup peanut butter", "1/3 cup honey", "2 tbsp chia seeds", "2 tbsp flaxseed meal", "Mini chocolate chips (optional)"],
            Instructions = ["Stir all ingredients together until combined.", "Chill 15 minutes.", "Roll into bite-sized balls and refrigerate."],
            Image = "",
            Tags = ["snack", "no-bake"],
            CookingTimeHours = 0,
            CookingTimeMinutes = 15,
            FavoritesCount = 0,
            CreatedAt = SeedDate,
            UpdatedAt = SeedDate
        }
    ];
}