// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Recipes.Database;

#nullable disable

namespace Recipes.Migrations
{
    [DbContext(typeof(RecipeDbContext))]
    [Migration("20250901083038_AddMoreSeededRecipes")]
    partial class AddMoreSeededRecipes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Recipes.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Start your day with energy",
                            Name = "Breakfast",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Refuel your body with a healthy lunch",
                            Name = "Lunch",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "End your day with a delicious dinner",
                            Name = "Dinner",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quick and easy snacks for any time",
                            Name = "Snack",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Recipes.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("CookingTimeHours")
                        .HasColumnType("integer");

                    b.Property<int>("CookingTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FavoritesCount")
                        .HasColumnType("integer");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Ingredients")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("Instructions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 20,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Fluffy pancakes perfect for breakfast.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "2 cups flour", "2 eggs", "1.5 cups milk", "2 tbsp sugar", "1 tsp baking powder", "Pinch of salt" },
                            Instructions = new[] { "Mix dry ingredients.", "Add eggs and milk.", "Whisk until smooth.", "Cook on griddle until golden." },
                            Name = "Classic Pancakes",
                            Tags = new[] { "breakfast", "pancakes" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 25,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "A healthy lunch salad with grilled chicken.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "2 chicken breasts", "Romaine lettuce", "Caesar dressing", "Croutons", "Parmesan cheese" },
                            Instructions = new[] { "Grill chicken.", "Chop lettuce.", "Mix all ingredients.", "Top with dressing and cheese." },
                            Name = "Chicken Caesar Salad",
                            Tags = new[] { "lunch", "salad" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 40,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Classic Italian pasta dish with rich meat sauce.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "200g spaghetti", "100g ground beef", "1 can tomato sauce", "1 onion", "2 cloves garlic", "Olive oil", "Salt", "Pepper" },
                            Instructions = new[] { "Cook spaghetti.", "Sauté onion and garlic.", "Add beef and cook until brown.", "Pour in tomato sauce and simmer.", "Serve sauce over spaghetti." },
                            Name = "Spaghetti Bolognese",
                            Tags = new[] { "dinner", "pasta" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 30,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Chewy cookies loaded with chocolate chips.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "1 cup butter", "1 cup sugar", "2 cups flour", "2 eggs", "1 tsp vanilla", "1 tsp baking soda", "2 cups chocolate chips" },
                            Instructions = new[] { "Preheat oven to 350°F (175°C).", "Cream butter and sugar.", "Add eggs and vanilla.", "Mix in flour and baking soda.", "Fold in chocolate chips.", "Drop by spoonfuls onto baking sheet.", "Bake for 10-12 minutes." },
                            Name = "Chocolate Chip Cookies",
                            Tags = new[] { "snack", "cookies" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 15,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Fresh salad with tomatoes, mozzarella, and basil.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "4 tomatoes", "200g mozzarella", "Fresh basil", "Olive oil", "Salt", "Pepper" },
                            Instructions = new[] { "Slice tomatoes and mozzarella.", "Layer with basil leaves.", "Drizzle with olive oil.", "Season with salt and pepper." },
                            Name = "Caprese Salad",
                            Tags = new[] { "lunch", "salad" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 20,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Quick and healthy vegetable stir-fry.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "Mixed vegetables (bell peppers, broccoli, carrots)", "2 tbsp soy sauce", "1 tbsp olive oil", "2 cloves garlic", "1 tsp ginger" },
                            Instructions = new[] { "Heat oil in a pan.", "Add garlic and ginger, sauté for 1 minute.", "Add vegetables and stir-fry until tender.", "Add soy sauce and cook for another 2 minutes." },
                            Name = "Vegetable Stir-Fry",
                            Tags = new[] { "dinner", "vegetarian" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Simple and nutritious breakfast toast with avocado.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "2 slices whole-grain bread", "1 ripe avocado", "Salt", "Pepper", "Lemon juice", "Chili flakes (optional)", "Olive oil (optional)" },
                            Instructions = new[] { "Toast the bread.", "Mash avocado with lemon juice, salt, and pepper.", "Spread on toast.", "Drizzle with olive oil and sprinkle chili flakes if using." },
                            Name = "Avocado Toast",
                            Tags = new[] { "breakfast", "quick" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 12,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Fluffy omelette filled with cheese.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "3 eggs", "2 tbsp milk", "1/2 cup shredded cheese", "1 tbsp butter", "Salt", "Pepper" },
                            Instructions = new[] { "Whisk eggs, milk, salt, and pepper.", "Melt butter in a pan.", "Pour eggs and cook until almost set.", "Add cheese, fold, and cook until melted." },
                            Name = "Cheese Omelette",
                            Tags = new[] { "breakfast", "eggs" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 15,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Classic cinnamon vanilla French toast.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "4 slices bread", "2 eggs", "1/2 cup milk", "1 tsp vanilla", "1/2 tsp cinnamon", "Butter", "Maple syrup" },
                            Instructions = new[] { "Whisk eggs, milk, vanilla, and cinnamon.", "Dip bread in mixture.", "Cook on buttered skillet until golden on both sides.", "Serve with maple syrup." },
                            Name = "French Toast",
                            Tags = new[] { "breakfast", "sweet" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Thick smoothie bowl topped with fruit and granola.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "1 cup frozen berries", "1 banana", "1/2 cup yogurt", "1/2 cup milk", "Granola", "Fresh fruit", "Chia seeds" },
                            Instructions = new[] { "Blend berries, banana, yogurt, and milk until thick.", "Pour into a bowl.", "Top with granola, fresh fruit, and chia seeds." },
                            Name = "Berry Smoothie Bowl",
                            Tags = new[] { "breakfast", "smoothie" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Layered yogurt parfait with granola and honey.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "1 cup yogurt", "1/2 cup granola", "1/2 cup mixed berries", "1 tbsp honey" },
                            Instructions = new[] { "Layer yogurt, granola, and berries in a glass.", "Drizzle honey on top.", "Serve immediately." },
                            Name = "Granola Parfait",
                            Tags = new[] { "breakfast", "no-cook" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 15,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Hearty triple-decker turkey club.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "3 slices bread", "Sliced turkey", "Bacon", "Lettuce", "Tomato", "Mayonnaise", "Butter" },
                            Instructions = new[] { "Toast bread and spread with mayo.", "Layer turkey, bacon, lettuce, and tomato.", "Stack and slice in half." },
                            Name = "Turkey Club Sandwich",
                            Tags = new[] { "lunch", "sandwich" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 20,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Protein-packed quinoa salad with fresh veggies.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "1 cup cooked quinoa", "Cherry tomatoes", "Cucumber", "Red onion", "Feta cheese", "Olives", "Olive oil", "Lemon juice", "Salt", "Pepper" },
                            Instructions = new[] { "Combine cooked quinoa and chopped vegetables.", "Crumble in feta and add olives.", "Dress with olive oil, lemon juice, salt, and pepper.", "Toss and serve." },
                            Name = "Quinoa Veggie Salad",
                            Tags = new[] { "lunch", "vegetarian" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 25,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Comforting tomato soup with a touch of cream.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "1 tbsp olive oil", "1 onion", "2 cloves garlic", "1 can crushed tomatoes", "1 cup vegetable broth", "1/4 cup cream", "Salt", "Pepper", "Basil" },
                            Instructions = new[] { "Sauté onion and garlic in olive oil.", "Add tomatoes and broth; simmer 10 minutes.", "Blend until smooth.", "Stir in cream, season, and garnish with basil." },
                            Name = "Creamy Tomato Soup",
                            Tags = new[] { "lunch", "soup" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Colorful veggie wrap with hummus.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "Large tortilla", "Hummus", "Bell peppers", "Cucumber", "Spinach", "Carrots", "Avocado", "Salt", "Pepper" },
                            Instructions = new[] { "Spread hummus on tortilla.", "Layer sliced veggies and avocado.", "Season, roll tightly, and slice in half." },
                            Name = "Veggie Wrap",
                            Tags = new[] { "lunch", "vegan" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Classic tuna salad perfect for sandwiches or greens.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "1 can tuna", "2 tbsp mayo", "1 tbsp mustard", "Celery", "Red onion", "Salt", "Pepper", "Lemon juice" },
                            Instructions = new[] { "Drain tuna and combine with chopped celery and onion.", "Mix in mayo, mustard, and lemon juice.", "Season with salt and pepper.", "Serve as a sandwich or over greens." },
                            Name = "Tuna Salad",
                            Tags = new[] { "lunch", "seafood" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 25,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Seasoned ground beef tacos with fresh toppings.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "500g ground beef", "Taco seasoning", "Taco shells", "Lettuce", "Tomato", "Cheddar", "Sour cream", "Salsa" },
                            Instructions = new[] { "Cook beef with taco seasoning.", "Warm taco shells.", "Assemble with toppings and serve." },
                            Name = "Beef Tacos",
                            Tags = new[] { "dinner", "mexican" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 20,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Lemon garlic grilled salmon fillets.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "2 salmon fillets", "2 tbsp olive oil", "2 cloves garlic", "Lemon", "Salt", "Pepper", "Fresh dill" },
                            Instructions = new[] { "Brush salmon with oil, garlic, salt, and pepper.", "Grill 3-4 minutes per side.", "Serve with lemon wedges and dill." },
                            Name = "Grilled Salmon",
                            Tags = new[] { "dinner", "seafood" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 35,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Creamy coconut chicken curry.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "500g chicken", "1 onion", "2 cloves garlic", "1 tbsp curry powder", "1 tsp ginger", "1 can coconut milk", "Oil", "Salt" },
                            Instructions = new[] { "Sauté onion, garlic, and ginger.", "Add chicken and brown.", "Stir in curry powder.", "Pour coconut milk and simmer until cooked." },
                            Name = "Chicken Curry",
                            Tags = new[] { "dinner", "curry" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 50,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Layers of pasta with veggies and cheese.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "Lasagna noodles", "Marinara sauce", "Zucchini", "Spinach", "Ricotta", "Mozzarella", "Parmesan", "Olive oil", "Salt", "Pepper" },
                            Instructions = new[] { "Sauté zucchini and spinach.", "Layer noodles, sauce, veggies, and cheeses.", "Bake at 375°F (190°C) for 30-35 minutes." },
                            Name = "Vegetable Lasagna",
                            Tags = new[] { "dinner", "vegetarian" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 20,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Quick fried rice with shrimp and vegetables.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "2 cups cooked rice", "200g shrimp", "Frozen peas and carrots", "2 eggs", "Soy sauce", "Sesame oil", "Green onions", "Garlic" },
                            Instructions = new[] { "Scramble eggs and set aside.", "Stir-fry garlic, shrimp, and veggies.", "Add rice, soy sauce, and sesame oil.", "Stir in eggs and green onions." },
                            Name = "Shrimp Fried Rice",
                            Tags = new[] { "dinner", "stir-fry" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 25,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Tender beef with vegetables in a savory sauce.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "300g beef strips", "Broccoli", "Bell peppers", "Soy sauce", "Garlic", "Ginger", "Cornstarch", "Vegetable oil" },
                            Instructions = new[] { "Marinate beef in soy sauce and cornstarch.", "Stir-fry beef until browned; remove.", "Cook veggies with garlic and ginger.", "Return beef, add sauce, and toss." },
                            Name = "Beef Stir-Fry",
                            Tags = new[] { "dinner", "asian" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 20,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Classic pizza with tomato, mozzarella, and basil.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "Pizza dough", "Tomato sauce", "Fresh mozzarella", "Fresh basil", "Olive oil", "Salt" },
                            Instructions = new[] { "Preheat oven to highest setting.", "Stretch dough and spread sauce.", "Top with mozzarella and bake until bubbly.", "Garnish with basil and olive oil." },
                            Name = "Margherita Pizza",
                            Tags = new[] { "dinner", "pizza" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 45,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Hearty lentil stew with vegetables.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "1 cup lentils", "1 onion", "2 carrots", "2 celery stalks", "2 cloves garlic", "1 can diced tomatoes", "Vegetable broth", "Bay leaf", "Salt", "Pepper" },
                            Instructions = new[] { "Sauté onion, carrots, and celery.", "Add garlic, lentils, tomatoes, broth, and bay leaf.", "Simmer until lentils are tender.", "Season and serve." },
                            Name = "Lentil Stew",
                            Tags = new[] { "dinner", "vegan" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 40,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Bell peppers filled with rice and beef.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "4 bell peppers", "1 cup cooked rice", "300g ground beef", "1 onion", "Tomato sauce", "Cheddar", "Salt", "Pepper" },
                            Instructions = new[] { "Sauté beef and onion; mix with rice and sauce.", "Stuff peppers and top with cheese.", "Bake at 375°F (190°C) for 25-30 minutes." },
                            Name = "Stuffed Bell Peppers",
                            Tags = new[] { "dinner", "bake" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 4,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Creamy avocado dip with lime and cilantro.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "2 ripe avocados", "1/2 onion", "1 tomato", "1 lime", "Cilantro", "Salt", "Pepper" },
                            Instructions = new[] { "Mash avocados.", "Stir in finely chopped onion, tomato, and cilantro.", "Add lime juice, salt, and pepper to taste." },
                            Name = "Guacamole",
                            Tags = new[] { "snack", "dip" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 4,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Smooth chickpea hummus with tahini.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "1 can chickpeas", "2 tbsp tahini", "1 clove garlic", "2 tbsp olive oil", "Lemon juice", "Salt", "Paprika" },
                            Instructions = new[] { "Blend chickpeas, tahini, garlic, lemon juice, and salt.", "Stream in olive oil until smooth.", "Garnish with paprika." },
                            Name = "Classic Hummus",
                            Tags = new[] { "snack", "vegan" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 4,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 15,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Toasted bread topped with tomato and basil.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "Baguette", "Tomatoes", "Garlic", "Basil", "Olive oil", "Salt", "Pepper", "Balsamic glaze (optional)" },
                            Instructions = new[] { "Toast sliced baguette.", "Mix chopped tomatoes with garlic, basil, oil, salt, and pepper.", "Spoon onto toast and drizzle glaze if desired." },
                            Name = "Bruschetta",
                            Tags = new[] { "snack", "appetizer" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 4,
                            CookingTimeHours = 1,
                            CookingTimeMinutes = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Moist banana bread loaf with walnuts.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "3 ripe bananas", "1/3 cup melted butter", "3/4 cup sugar", "1 egg", "1 tsp vanilla", "1 tsp baking soda", "Pinch of salt", "1.5 cups flour", "1/2 cup walnuts" },
                            Instructions = new[] { "Mash bananas and mix with butter and sugar.", "Beat in egg and vanilla.", "Stir in baking soda, salt, and flour.", "Fold in walnuts.", "Bake in loaf pan at 350°F (175°C) for 50-60 minutes." },
                            Name = "Banana Bread",
                            Tags = new[] { "snack", "bake" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 4,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 30,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Fudgy chocolate brownies with crackly top.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "1/2 cup butter", "1 cup sugar", "2 eggs", "1 tsp vanilla", "1/3 cup cocoa powder", "1/2 cup flour", "1/4 tsp salt", "1/4 tsp baking powder" },
                            Instructions = new[] { "Melt butter and mix with sugar.", "Beat in eggs and vanilla.", "Stir in dry ingredients.", "Bake at 350°F (175°C) for 20-25 minutes." },
                            Name = "Chocolate Brownies",
                            Tags = new[] { "snack", "chocolate" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 1,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 20,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Eggs, potatoes, and cheese wrapped in a warm tortilla.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "Large tortilla", "2 eggs", "1/2 cup diced potatoes", "1/4 cup shredded cheese", "Salsa", "Salt", "Pepper", "Oil" },
                            Instructions = new[] { "Cook diced potatoes in oil until tender.", "Scramble eggs and season.", "Warm tortilla and fill with potatoes, eggs, cheese, and salsa.", "Roll up and serve." },
                            Name = "Breakfast Burrito",
                            Tags = new[] { "breakfast", "wrap" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 1,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 40,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Warm baked oats with berries and cinnamon.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "2 cups rolled oats", "1 tsp baking powder", "1 tsp cinnamon", "Pinch of salt", "2 cups milk", "1 egg", "2 tbsp maple syrup", "1 cup mixed berries" },
                            Instructions = new[] { "Preheat oven to 350°F (175°C).", "Mix dry ingredients.", "Whisk milk, egg, and maple syrup.", "Combine with oats and fold in berries.", "Bake 30–35 minutes until set." },
                            Name = "Baked Oatmeal",
                            Tags = new[] { "breakfast", "oats" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 1,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 30,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Eggs poached in a spiced tomato pepper sauce.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "2 tbsp olive oil", "1 onion", "1 bell pepper", "2 cloves garlic", "1 tsp cumin", "1 tsp paprika", "1 can crushed tomatoes", "4 eggs", "Salt", "Pepper", "Parsley" },
                            Instructions = new[] { "Sauté onion and pepper in oil.", "Add garlic and spices.", "Pour in tomatoes and simmer.", "Make wells and crack eggs; cover until set.", "Season and garnish with parsley." },
                            Name = "Shakshuka",
                            Tags = new[] { "breakfast", "eggs" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 1,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "No-cook oats soaked overnight with chia and fruit.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "1/2 cup rolled oats", "1 tbsp chia seeds", "1/2 cup milk", "1/4 cup yogurt", "1 tsp honey", "Fresh fruit" },
                            Instructions = new[] { "Combine oats, chia, milk, yogurt, and honey in a jar.", "Stir, cover, and refrigerate overnight.", "Top with fruit before serving." },
                            Name = "Overnight Oats",
                            Tags = new[] { "breakfast", "no-cook" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 2,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 15,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Crisp cucumber, tomato, olives, and feta with oregano.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "Cucumber", "Tomatoes", "Red onion", "Kalamata olives", "Feta", "Olive oil", "Red wine vinegar", "Oregano", "Salt", "Pepper" },
                            Instructions = new[] { "Chop vegetables and combine with olives and feta.", "Dress with oil, vinegar, oregano, salt, and pepper.", "Toss and serve." },
                            Name = "Greek Salad",
                            Tags = new[] { "lunch", "salad" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 2,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 12,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Classic bacon, lettuce, and tomato on toasted bread.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "2 slices bread", "Bacon", "Lettuce", "Tomato", "Mayonnaise", "Salt", "Pepper" },
                            Instructions = new[] { "Cook bacon until crisp.", "Toast bread and spread with mayo.", "Layer bacon, lettuce, and tomato; season and serve." },
                            Name = "BLT Sandwich",
                            Tags = new[] { "lunch", "sandwich" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 2,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 35,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Hearty Italian vegetable and bean soup.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "Olive oil", "Onion", "Carrot", "Celery", "Garlic", "Diced tomatoes", "Vegetable broth", "Cannellini beans", "Small pasta", "Zucchini", "Spinach", "Salt", "Pepper" },
                            Instructions = new[] { "Sauté onion, carrot, celery, and garlic.", "Add tomatoes and broth; simmer.", "Stir in beans and pasta; cook until tender.", "Add zucchini and spinach; season and serve." },
                            Name = "Minestrone Soup",
                            Tags = new[] { "lunch", "soup" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Customizable nuts, seeds, dried fruit, and chocolate.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "Almonds", "Cashews", "Pumpkin seeds", "Raisins", "Dried cranberries", "Dark chocolate chips", "Sea salt" },
                            Instructions = new[] { "Combine all ingredients in a bowl.", "Toss to mix and store in an airtight container." },
                            Name = "Trail Mix",
                            Tags = new[] { "snack", "no-cook" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Fresh seasonal fruit with a honey-lime dressing.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "Strawberries", "Blueberries", "Pineapple", "Grapes", "Kiwi", "Honey", "Lime juice", "Mint" },
                            Instructions = new[] { "Chop fruit and combine in a bowl.", "Whisk honey with lime juice.", "Pour over fruit and toss with chopped mint." },
                            Name = "Fruit Salad",
                            Tags = new[] { "snack", "fruit" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Simple snack board with assorted cheeses and crackers.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "Assorted crackers", "Cheddar", "Brie", "Gouda", "Grapes", "Honey" },
                            Instructions = new[] { "Arrange cheeses and crackers on a board.", "Add grapes and a drizzle of honey." },
                            Name = "Cheese and Crackers",
                            Tags = new[] { "snack", "board" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 4,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Greek yogurt ranch dip served with crunchy vegetables.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "1 cup Greek yogurt", "1 tsp dried dill", "1/2 tsp garlic powder", "1/2 tsp onion powder", "1 tsp lemon juice", "Salt", "Pepper", "Assorted veggie sticks" },
                            Instructions = new[] { "Mix yogurt with dill, garlic and onion powder, and lemon juice.", "Season with salt and pepper.", "Serve with veggie sticks." },
                            Name = "Yogurt Ranch Dip with Veggies",
                            Tags = new[] { "snack", "dip" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 1,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 15,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Crispy tortilla filled with scrambled eggs, cheese, and veggies.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "Large tortilla", "2 eggs", "1/3 cup shredded cheese", "Bell peppers", "Spinach", "Butter or oil", "Salt", "Pepper", "Salsa (optional)" },
                            Instructions = new[] { "Scramble eggs and season.", "Warm tortilla in a pan; add cheese, eggs, and veggies.", "Fold and cook until golden on both sides.", "Serve with salsa if desired." },
                            Name = "Breakfast Quesadilla",
                            Tags = new[] { "breakfast", "wrap" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 2,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 15,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "Protein-packed bowl with chickpeas, veggies, and lemon-tahini dressing.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "1 can chickpeas", "Cherry tomatoes", "Cucumber", "Red onion", "Kalamata olives", "Parsley", "Feta (optional)", "Olive oil", "Lemon juice", "Tahini", "Salt", "Pepper" },
                            Instructions = new[] { "Rinse and drain chickpeas.", "Chop vegetables and parsley.", "Whisk olive oil, lemon juice, tahini, salt, and pepper.", "Combine all and toss with dressing; top with feta if using." },
                            Name = "Mediterranean Chickpea Bowl",
                            Tags = new[] { "lunch", "vegetarian" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 4,
                            CookingTimeHours = 0,
                            CookingTimeMinutes = 15,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = 3,
                            Description = "No-bake oats, peanut butter, and honey bites.",
                            FavoritesCount = 0,
                            Image = "",
                            Ingredients = new[] { "1 cup rolled oats", "1/2 cup peanut butter", "1/3 cup honey", "2 tbsp chia seeds", "2 tbsp flaxseed meal", "Mini chocolate chips (optional)" },
                            Instructions = new[] { "Stir all ingredients together until combined.", "Chill 15 minutes.", "Roll into bite-sized balls and refrigerate." },
                            Name = "Peanut Butter Energy Bites",
                            Tags = new[] { "snack", "no-bake" },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Recipes.Models.RecipeFavorite", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeFavorites");
                });

            modelBuilder.Entity("Recipes.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanSubmitRecipes")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("Roles")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanSubmitRecipes = true,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "testuser",
                            Email = "testuser@test.com",
                            FirstName = "Seed",
                            LastName = "User",
                            PasswordHash = "$2a$12$5TWK64v6F6PcHnH9d3b1QegvN3M218yWqbxwFJnROB6J7DenFONsC",
                            Roles = new[] { 1, 0 },
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Recipes.Models.Recipe", b =>
                {
                    b.HasOne("Recipes.Models.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recipes.Models.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Recipes.Models.RecipeFavorite", b =>
                {
                    b.HasOne("Recipes.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recipes.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Recipes.Models.Category", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("Recipes.Models.User", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
